name: mitraku_kolektor
description: KSU MITRAKU

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^1.0.0+5
  barcode_scan: ^2.0.1
  # camera: ^0.5.8+2
  carousel_pro: ^1.0.0
  connectivity: ^0.4.8+2
  datetime_picker_formfield: ^1.0.0
  device_info: ^0.4.2+1
  dio: ^3.0.9
  exif: ^1.0.3
  extended_image: ^0.6.8
  firebase_messaging: ^6.0.13
  flare_flutter: ^2.0.3
  #flutter_easyloading: ^1.1.4
  flutter_easyloading: ^3.0.3
  flutter_icons: ^1.1.0
  flutter_local_notifications: ^1.4.4+1
  flutter_masked_text: ^0.8.0
  flutter_native_image: ^0.0.5+2
  flutter_polyline_points: ^0.2.4
  flutter_rating_bar: ^3.0.1+1
  flutter_screenutil: ^0.4.2
  geocoder: ^0.2.1
  get_it: ^4.0.2
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.30
  http: ^0.12.0+4
  image_gallery_saver: ^1.5.0
  intl: ^0.17.0
  location: ^3.0.2
  lottie: ^0.6.0
  permission_handler: ^5.0.0+hotfix.3
  pin_code_fields: ^2.5.1
  provider: ^4.1.3
  qr_flutter: ^3.2.0
  rxdart: ^0.24.1
  screenshot: ^0.2.0
  share: ^0.6.4+3
  shared_preferences: ^0.5.6+3
  steel_crypt: ^1.7.1+1
  url_launcher: ^5.5.0
  webview_flutter: ^0.3.22+1
  flutter_ticket_widget: ^0.0.1
  # flutter_svg: ^0.12.1
  fluttertagselector: ^0.1.0
  flutter_exif_rotation: ^0.4.1
  sqflite: ^2.0.0+3
  path_provider: ^1.1.0
  flutter_dash: ^0.0.1
  blue_thermal_printer: ^1.1.3
  flutter_blue: ^0.7.0
  flutter_mobx: ^2.0.1
  two_letter_icon: ^0.0.1
  badges: ^2.0.1
  wifi_info_flutter: ^2.0.2
  dart_ipify: ^1.1.1
  countup: ^0.1.3
  app_settings: 4.1.1
  path: ^1.8.0
  filesystem_picker: ^2.0.0
  flutter_html: 0.11.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider: ^1.4.1
  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9
  flutter_staggered_animations: ^1.0.0
  change_app_package_name: ^0.1.2


flutter_native_splash:
  color: "E11E3C"
  android_disable_fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - assets/merchant/
    - assets/lottie/
    - assets/database/sqlite_koperasi.db
  fonts:
    - family: CustomIcons
      fonts:      
        - asset: assets/icon/BottombarIconsV2.ttf
    # fonts:
    # - family: Ubuntu
    #   fonts:
    #     - asset: assets/fonts/Ubuntu-Light.ttf
    #       weight: 500
    #     - asset: assets/fonts/Ubuntu-Regular.ttf
    #       weight: 600
    #     - asset: assets/fonts/Ubuntu-Medium.ttf
    #       weight: 700
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/Poppins-Regular.ttf
    #       weight: 500
    #     - asset: assets/fonts/Poppins-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Poppins-Bold.ttf
    #       weight: 700
    # - family: OpenSans
    #   fonts:
    #     - asset: assets/fonts/OpenSans-Regular.ttf
    #       weight: 500
    #     - asset: assets/fonts/OpenSans-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/OpenSans-Bold.ttf
    #       weight: 700
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
