name: mitraku_kolektor
description: KSU MITRAKU

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.8
  app_settings: ^4.3.0
  badges: ^3.1.2
  barcode_scan2: ^4.2.4
  blue_thermal_printer: ^1.2.3
  bootstrap_icons: ^1.10.5+2
  connectivity_plus: ^3.0.6
  countup: ^0.1.4
  device_info_plus: ^6.0.0
  dio: ^5.3.2
  exif: ^3.1.4
  filesystem_picker: ^3.1.0
  firebase_messaging: ^14.6.7
  flare_flutter: ^3.0.2
  flutter_dash: ^1.0.0
  flutter_easyloading: ^3.0.5
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^15.1.1
  flutter_localization: ^0.1.13
  flutter_masked_text2: ^0.9.1
  flutter_native_image: ^0.0.6+1
  flutter_screenutil: ^5.9.0
  geocoder2: ^1.4.0
  get_it: ^7.6.4
  google_fonts: ^4.0.0
  google_maps_flutter: 2.0.0
  iconsax: ^0.0.8
  intl: ^0.18.0
  location: ^4.4.0
  lottie: ^2.6.0
  path_provider: 2.0.2
  permission_handler: ^10.4.3
  pin_code_fields: ^8.0.1
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  showcaseview: ^2.0.3
  sqflite: ^2.3.0
  steel_crypt: ^3.0.0+1
  syncfusion_flutter_datepicker: ^22.2.12
  ticket_widget: ^0.0.1
  webview_flutter: ^4.2.4
  firebase_core: ^2.15.1
  encrypt: ^5.0.1
  url_launcher: 6.0.5
  flutter_initicon: ^3.0.0+1
  geocoding: ^2.1.0
  shorebird_code_push: ^1.1.3
  restart_app: ^1.2.1
  
  

dev_dependencies:
  carousel_slider: ^4.2.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_staggered_animations: ^1.0.0
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "E11E3C"
  android_disable_fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - assets/merchant/
    - assets/lottie/
    - assets/database/sqlite_koperasi.db
  fonts:
    - family: CustomIcons
      fonts:      
        - asset: assets/icon/BottombarIconsV2.ttf
    # fonts:
    # - family: Ubuntu
    #   fonts:
    #     - asset: assets/fonts/Ubuntu-Light.ttf
    #       weight: 500
    #     - asset: assets/fonts/Ubuntu-Regular.ttf
    #       weight: 600
    #     - asset: assets/fonts/Ubuntu-Medium.ttf
    #       weight: 700
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/Poppins-Regular.ttf
    #       weight: 500
    #     - asset: assets/fonts/Poppins-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Poppins-Bold.ttf
    #       weight: 700
    # - family: OpenSans
    #   fonts:
    #     - asset: assets/fonts/OpenSans-Regular.ttf
    #       weight: 500
    #     - asset: assets/fonts/OpenSans-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/OpenSans-Bold.ttf
    #       weight: 700
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
